### ISSUE TITLE
List of Opportunities (HTML/CSS milestone)

### ISSUE THREAD

**Issue by n00721843** [av-jones/netassets#12]
- [ ] Table listing out volunteering opportunities in system is displayed
- [ ] This page can only be viewed by logged-in admin
**_Each volunteer listing has the following links or buttons:_**
- [ ] Edit Opportunity
- [ ] Delete Opportunity
- [ ] View Opportunity Matches
_**Overall table has the following links or buttons:**_
- [ ] Change Opportunity Filter
- [ ] Search Opportunities
- [ ] Add New Opportunity
