### ISSUE TITLE
List of Opportunities (CRUD - Create milestone)

### ISSUE THREAD

**Issue by n00721843** [av-jones/netassets#13]
- [ ] The "Add New Opportunity" link on the _List of Opportunities_ page works
- [ ] Clicking the "Add New Opportunity" link takes the user to an _Add New Opportunity_ page
- [ ] Completing the form adds the new opportunity to the _List of Opportunities_ list, via database
- [ ] This page can only be viewed by a logged-in administrator
### properties
The following are able to be added at the _Add New Volunteer_ page:
- [ ] Name
- [ ] Keyword(s)
- [ ] Center
- [ ] Date of opportunity

### functionality doublecheck
- [ ] data validation for all fields
**_List properties accept list inputs:_**
- [ ] Keyword(s)
- [ ] Start time/end time of opportunity, if relevant
