### ISSUE TITLE
List of Opportunities (CRUD - Update milestone)

### ISSUE THREAD

**Issue by n00721843** [av-jones/netassets#14]
- [ ] Each "Edit Opportunity" link on the _List of Opportunities_ page works
- [ ] Clicking an "Edit Opportunity" link takes the user to an _Edit Opportunity_ page
- [ ] Completing the form edits the opportunity in the database
- [ ] This page can only be viewed by a logged-in administrator
### properties
The following are able to be edited at the _Edit Opportunity_ page:
- [ ] Name
- [ ] Keyword(s)
- [ ] Center
- [ ] Date of opportunity

### functionality doublecheck
- [ ] data validation for all fields
**_List properties accept list inputs:_**
- [ ] Keyword(s)
- [ ] Start time/end time of opportunity, if relevant
