### ISSUE TITLE
List of Opportunities (CRUD - Read milestone)

### ISSUE THREAD

**Issue by n00721843** [av-jones/netassets#15]
- [ ] _List of Opportunities_ page properly displays opportunities in database
- [ ] _List of Opportunities_ page has a default filter of "Most Recent (60 Days)"
- [ ] Displays an error message saying "search returned no results" if a combination of search query and filter resulted in an empty list being displayed
