### ISSUE TITLE
List of Opportunities (filters milestone)

### ISSUE THREAD

**Issue by n00721843** [av-jones/netassets#17]
- [ ] Link "Change Opportunity Filter" works on _List of Opportunities_ page
- [ ] The default filter on the _List of Opportunities_ is "Most Recent (60 Days)"
- [ ] Changes to the currently selected filter are saved throughout the session
- [ ] This page can only be viewed by a logged-in administrator
- [ ] If selecting a filter would result in an empty list being displayed in the _List of Volunteers_ page, instead show a message letting the user know their search result had no results
_**The following Volunteer filters are available and working:**_
- [ ] Most Recent (60 Days)
- [ ] By Center
