### ISSUE TITLE
List of Volunteers (filters milestone) [1.1.6]

### ISSUE THREAD

**Issue by n00721843** [av-jones/netassets#6]
- [ ] Link "Change Volunteer Filter" works on _List of Volunteers_ page
- [ ] The default filter on the _List of Volunteers_ is "All"
- [ ] Changes to the currently selected filter are saved throughout the session
_**The following Volunteer filters are available and working:**_
- [ ] Approved/Pending Approval
- [ ] Approved
- [ ] Pending Approval
- [ ] Disapproved
- [ ] Inactive
- [ ] All
