### ISSUE TITLE
List of Volunteers (CRUD - Create milestone)

### ISSUE THREAD

**Issue by n00721843** [av-jones/netassets#7]
- [ ] The "Add New Volunteer" link on the _List of Volunteers page_ works
- [ ] Clicking the "Add New Volunteer" link takes the user to an _Add New Volunteer_ page
- [ ] Completing the form adds the new volunteer to the _List of Volunteers_ list, via database
### properties
The following are able to be added at the _Add New Volunteer_ page:
- [ ] First Name
- [ ] Last Name
- [ ] Username
- [ ] Password
- [ ] Center(s) where the volunteer prefers to work at
- [ ] Skills/Interest
- [ ] Availability times
- [ ] Home phone
- [ ] Work phone
- [ ] Cell phone
- [ ] email address
- [ ] Educational background
- [ ] Current licenses
- [ ] emergency contact name
- [ ] emergency contact home phone
- [ ] emergency contact work phone
- [ ] emergency contact email address
- [ ] emergency contact mailing address
- [ ] whether or not there's a copy of the volunteer's driver's license on file
- [ ] whether or not there's a copy of the volunteer's social security card on file
- [ ] volunteer's approval status (Approved, Pending Approval, Disapproved, Inactive)

### functionality doublecheck
- [ ] data validation for all fields
**_List properties accept list inputs:_**
- [ ] Centers
- [ ] Skills/Interests
- [ ] Availability times
- [ ] Educational background
- [ ] Current licenses
